sudo: required

services: 
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run react-test npm test  -- --coverage

after_success:
  - docker build -t multi-container-client   ./client
  - docker build -t multi-container-nginx   ./nginx
  - docker build -t multi-container-server   ./server
  - docker build -t multi-container-worker   ./worker
  
  
